services:
  security:
    image: sevenhallo-security:latest
    container_name: security
    command: start-dev
    ports:
      - "8003:8003"
    networks:
      - sevenhallo

volumes:
  security:

networks:
  sevenhallo:
    driver: bridge
    external: true
